use anyhow::Result;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::config::{Config, config_field_docs, default_rule_switches, render_config_schema};
use crate::quality::QUALITY_RULES;
use crate::registry::{builtin_adapters, builtin_rule_groups};

fn format_default_value(value: &str) -> String {
    value.to_string()
}

pub fn render_config_reference() -> String {
    let _defaults = Config::default();
    let mut lines = vec![
        "# Config Reference".to_string(),
        String::new(),
        "<!-- Generated by seogeo docs generate. Do not edit by hand. -->".to_string(),
        String::new(),
        "The canonical config surface is the versioned nested format with `version = 1`. The legacy flat top-level keys remain supported for compatibility and are validated with the same strictness."
            .to_string(),
        "Compatibility mode is no longer silent: commands emit `CFGDEP001` warnings whenever legacy flat keys or legacy `[rules]` boolean toggles are used."
            .to_string(),
        "The `plugin_settings` table is reserved until a plugin publishes a registered settings schema; no built-in schemas are currently shipped."
            .to_string(),
        String::new(),
        "Generated JSON Schema: `docs/config.schema.json`".to_string(),
        String::new(),
        "Editor hint: add `#:schema ../config.schema.json` at the top of a config file stored under `docs/examples/` or adjust the relative path for your repository layout."
            .to_string(),
        String::new(),
        "## Canonical Example".to_string(),
        String::new(),
        "```toml".to_string(),
        "version = 1".to_string(),
        String::new(),
        "[site]".to_string(),
        "url = \"https://example.com\"".to_string(),
        "source_dir = \"dist\"".to_string(),
        "adapter = \"astro-dist\"".to_string(),
        String::new(),
        "[runtime]".to_string(),
        "engine = \"http\"".to_string(),
        "use_sitemap = true".to_string(),
        String::new(),
        "[policy]".to_string(),
        "ignore_rules = [\"SCH012\"]".to_string(),
        String::new(),
        "[rules.html]".to_string(),
        "enabled = true".to_string(),
        String::new(),
        "[rules.links]".to_string(),
        "enabled = true".to_string(),
        "min_inbound_links = 1".to_string(),
        String::new(),
        "[rules.schema]".to_string(),
        "enabled = true".to_string(),
        "require_title_alignment = true".to_string(),
        String::new(),
        "[output]".to_string(),
        "baseline_file = \".seogeo-baseline.json\"".to_string(),
        String::new(),
        "[quality]".to_string(),
        "coverage_threshold = 85".to_string(),
        "```".to_string(),
        String::new(),
        "## Editor And CI Consumption".to_string(),
        String::new(),
        "- Editor schema hint: use a TOML schema comment such as `#:schema ./docs/config.schema.json` or a relative equivalent for the file you are editing."
            .to_string(),
        "- CI validation: run `cargo run -q -p seogeo-cli -- config print . --format json > /dev/null` to fail fast on invalid, unknown, or unsupported config keys."
            .to_string(),
        "- Canonical normalization: `cargo run -q -p seogeo-cli -- config print . --format toml` renders the fully resolved versioned surface after defaults and `extends` merges."
            .to_string(),
        "- Migration diagnostics: parse the `warnings` array from `seogeo config print --format json` and treat `CFGDEP001` as a tracked deprecation signal in CI."
            .to_string(),
        String::new(),
        "## Top-Level Keys".to_string(),
        String::new(),
    ];
    for field in config_field_docs() {
        lines.push(format!("## `{}`", field.key));
        lines.push(String::new());
        lines.push(format!(
            "- Default: {}",
            format_default_value(field.default_value)
        ));
        lines.push(format!("- Meaning: {}", field.description));
        lines.push(String::new());
    }
    lines.push("## `checks`".to_string());
    lines.push(String::new());
    lines.push("Built-in rule-group toggles. Unknown plugin rule groups default to enabled unless explicitly disabled.".to_string());
    lines.push(String::new());
    for (rule_name, enabled) in default_rule_switches() {
        lines.push(format!("- `{}`: default `{}`", rule_name, enabled));
    }
    lines.push(String::new());
    lines.join("\n")
}

pub fn render_rule_reference() -> String {
    let mut lines = vec![
        "# Rule Inventory".to_string(),
        String::new(),
        "<!-- Generated by seogeo docs generate. Do not edit by hand. -->".to_string(),
        String::new(),
        format!(
            "`seogeo` currently ships {} built-in rule groups.",
            builtin_rule_groups().len()
        ),
        String::new(),
    ];
    for group in builtin_rule_groups() {
        lines.push(format!("## `{}`", group.name));
        lines.push(String::new());
        if !group.description.is_empty() {
            lines.push(group.description.to_string());
            lines.push(String::new());
        }
        for rule in group.rules {
            lines.push(format!("- `{}`: {}", rule.rule_id, rule.summary));
        }
        lines.push(String::new());
    }
    lines.push("## Internal Quality".to_string());
    lines.push(String::new());
    for (rule_id, summary) in QUALITY_RULES {
        lines.push(format!("- `{}`: {}", rule_id, summary));
    }
    lines.push(String::new());
    lines.join("\n")
}

pub fn render_adapter_reference() -> String {
    let mut lines = vec![
        "# Adapter Reference".to_string(),
        String::new(),
        "<!-- Generated by seogeo docs generate. Do not edit by hand. -->".to_string(),
        String::new(),
        "Adapters decide which directory should be inventoried for a given repository path."
            .to_string(),
        String::new(),
        "## Built-in Adapters".to_string(),
        String::new(),
    ];
    for adapter in builtin_adapters() {
        lines.push(format!("## `{}`", adapter.name));
        lines.push(String::new());
        lines.push(format!("- Priority: `{}`", adapter.priority));
        lines.push(format!("- Purpose: {}", adapter.description));
        lines.push(String::new());
    }
    lines.push("## Plugins".to_string());
    lines.push(String::new());
    lines.push("The Rust CLI is the canonical entrypoint. Plugin validation is handled natively and plugin execution remains bounded by the Rust contracts and adapter model.".to_string());
    lines.push(String::new());
    lines.join("\n")
}

pub fn reference_documents(cli_reference: String) -> Result<BTreeMap<String, String>> {
    Ok(BTreeMap::from([
        ("docs/cli.md".to_string(), cli_reference),
        ("docs/config.md".to_string(), render_config_reference()),
        (
            "docs/config.schema.json".to_string(),
            render_config_schema()?,
        ),
        ("docs/rules.md".to_string(), render_rule_reference()),
        ("docs/adapters.md".to_string(), render_adapter_reference()),
    ]))
}

pub fn write_reference_documents(root: &Path, cli_reference: String) -> Result<Vec<PathBuf>> {
    let mut changed = Vec::new();
    for (relative_path, expected) in reference_documents(cli_reference)? {
        let path = root.join(relative_path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        let current = fs::read_to_string(&path).ok();
        if current.as_deref() == Some(expected.as_str()) {
            continue;
        }
        fs::write(&path, expected)?;
        changed.push(path);
    }
    Ok(changed)
}

pub fn find_reference_doc_drift(root: &Path, cli_reference: String) -> Result<Vec<PathBuf>> {
    let mut drifted = Vec::new();
    for (relative_path, expected) in reference_documents(cli_reference)? {
        let path = root.join(relative_path);
        let actual = fs::read_to_string(&path).ok();
        if actual.as_deref() != Some(expected.as_str()) {
            drifted.push(path);
        }
    }
    Ok(drifted)
}

#[cfg(test)]
mod tests {
    use super::{
        find_reference_doc_drift, render_adapter_reference, render_config_reference,
        render_rule_reference, write_reference_documents,
    };
    use crate::config::render_config_schema;

    #[test]
    fn renders_reference_sections() {
        assert!(render_config_reference().contains("# Config Reference"));
        assert!(render_config_schema().unwrap().contains("\"$schema\""));
        assert!(render_rule_reference().contains("# Rule Inventory"));
        assert!(render_rule_reference().contains("## Internal Quality"));
        assert!(render_adapter_reference().contains("# Adapter Reference"));
    }

    #[test]
    fn detects_drift_against_generated_docs() {
        let temp_dir = tempfile::tempdir().unwrap();
        let cli_reference = "# CLI Reference\n".to_string();
        write_reference_documents(temp_dir.path(), cli_reference.clone()).unwrap();
        assert!(
            find_reference_doc_drift(temp_dir.path(), cli_reference)
                .unwrap()
                .is_empty()
        );
    }
}
