use anyhow::Result;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::config::{Config, config_field_docs, default_rule_switches};
use crate::quality::QUALITY_RULES;
use crate::registry::{builtin_adapters, builtin_rule_groups};

fn format_default_value(value: &str) -> String {
    value.to_string()
}

pub fn render_config_reference() -> String {
    let _defaults = Config::default();
    let mut lines = vec![
        "# Config Reference".to_string(),
        String::new(),
        "<!-- Generated by seogeo docs generate. Do not edit by hand. -->".to_string(),
        String::new(),
        "## Top-Level Keys".to_string(),
        String::new(),
    ];
    for field in config_field_docs() {
        lines.push(format!("## `{}`", field.key));
        lines.push(String::new());
        lines.push(format!(
            "- Default: {}",
            format_default_value(field.default_value)
        ));
        lines.push(format!("- Meaning: {}", field.description));
        lines.push(String::new());
    }
    lines.push("## `checks`".to_string());
    lines.push(String::new());
    lines.push("Built-in rule-group toggles. Unknown plugin rule groups default to enabled unless explicitly disabled.".to_string());
    lines.push(String::new());
    for (rule_name, enabled) in default_rule_switches() {
        lines.push(format!("- `{}`: default `{}`", rule_name, enabled));
    }
    lines.push(String::new());
    lines.join("\n")
}

pub fn render_rule_reference() -> String {
    let mut lines = vec![
        "# Rule Inventory".to_string(),
        String::new(),
        "<!-- Generated by seogeo docs generate. Do not edit by hand. -->".to_string(),
        String::new(),
        format!(
            "`seogeo` currently ships {} built-in rule groups.",
            builtin_rule_groups().len()
        ),
        String::new(),
    ];
    for group in builtin_rule_groups() {
        lines.push(format!("## `{}`", group.name));
        lines.push(String::new());
        if !group.description.is_empty() {
            lines.push(group.description.to_string());
            lines.push(String::new());
        }
        for rule in group.rules {
            lines.push(format!("- `{}`: {}", rule.rule_id, rule.summary));
        }
        lines.push(String::new());
    }
    lines.push("## Internal Quality".to_string());
    lines.push(String::new());
    for (rule_id, summary) in QUALITY_RULES {
        lines.push(format!("- `{}`: {}", rule_id, summary));
    }
    lines.push(String::new());
    lines.join("\n")
}

pub fn render_adapter_reference() -> String {
    let mut lines = vec![
        "# Adapter Reference".to_string(),
        String::new(),
        "<!-- Generated by seogeo docs generate. Do not edit by hand. -->".to_string(),
        String::new(),
        "Adapters decide which directory should be inventoried for a given repository path."
            .to_string(),
        String::new(),
        "## Built-in Adapters".to_string(),
        String::new(),
    ];
    for adapter in builtin_adapters() {
        lines.push(format!("## `{}`", adapter.name));
        lines.push(String::new());
        lines.push(format!("- Priority: `{}`", adapter.priority));
        lines.push(format!("- Purpose: {}", adapter.description));
        lines.push(String::new());
    }
    lines.push("## Plugins".to_string());
    lines.push(String::new());
    lines.push("The Rust CLI is the canonical entrypoint. Plugin validation is handled natively and plugin execution remains bounded by the Rust contracts and adapter model.".to_string());
    lines.push(String::new());
    lines.join("\n")
}

pub fn reference_documents(cli_reference: String) -> BTreeMap<String, String> {
    BTreeMap::from([
        ("docs/cli.md".to_string(), cli_reference),
        ("docs/config.md".to_string(), render_config_reference()),
        ("docs/rules.md".to_string(), render_rule_reference()),
        ("docs/adapters.md".to_string(), render_adapter_reference()),
    ])
}

pub fn write_reference_documents(root: &Path, cli_reference: String) -> Result<Vec<PathBuf>> {
    let mut changed = Vec::new();
    for (relative_path, expected) in reference_documents(cli_reference) {
        let path = root.join(relative_path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        let current = fs::read_to_string(&path).ok();
        if current.as_deref() == Some(expected.as_str()) {
            continue;
        }
        fs::write(&path, expected)?;
        changed.push(path);
    }
    Ok(changed)
}

pub fn find_reference_doc_drift(root: &Path, cli_reference: String) -> Result<Vec<PathBuf>> {
    let mut drifted = Vec::new();
    for (relative_path, expected) in reference_documents(cli_reference) {
        let path = root.join(relative_path);
        let actual = fs::read_to_string(&path).ok();
        if actual.as_deref() != Some(expected.as_str()) {
            drifted.push(path);
        }
    }
    Ok(drifted)
}

#[cfg(test)]
mod tests {
    use super::{
        find_reference_doc_drift, render_adapter_reference, render_config_reference,
        render_rule_reference, write_reference_documents,
    };

    #[test]
    fn renders_reference_sections() {
        assert!(render_config_reference().contains("# Config Reference"));
        assert!(render_rule_reference().contains("# Rule Inventory"));
        assert!(render_rule_reference().contains("## Internal Quality"));
        assert!(render_adapter_reference().contains("# Adapter Reference"));
    }

    #[test]
    fn detects_drift_against_generated_docs() {
        let temp_dir = tempfile::tempdir().unwrap();
        let cli_reference = "# CLI Reference\n".to_string();
        write_reference_documents(temp_dir.path(), cli_reference.clone()).unwrap();
        assert!(
            find_reference_doc_drift(temp_dir.path(), cli_reference)
                .unwrap()
                .is_empty()
        );
    }
}
