#[path = "quality/docs.rs"]
mod docs_audit;
#[path = "quality/rust.rs"]
mod rust_audit;
#[path = "quality/tooling.rs"]
mod tooling_audit;

use aexeo_contracts::{Finding, FindingScope};
use anyhow::Result;
use std::path::Path;

use crate::docs::find_reference_doc_drift;

pub const QUALITY_RULES: &[(&str, &str)] = &[
    ("QLT004", "missing required project documentation file"),
    ("QLT005", "built-in rule group missing from docs/rules.md"),
    (
        "QLT007",
        "generated docs drift from code and must be regenerated",
    ),
    ("QLT009", "missing Cargo workspace manifest"),
    ("QLT010", "missing Rust build script"),
    ("QLT011", "missing performance budget file"),
    ("QLT012", "missing Rust CLI integration test coverage"),
    ("QLT013", "missing install script"),
    ("QLT014", "missing local CI script"),
    ("QLT015", "missing git hook installation script"),
    ("QLT016", "missing pre-commit hook"),
    ("QLT017", "missing pre-push hook"),
    (
        "QLT018",
        "debug or placeholder macro in non-test Rust source",
    ),
    ("QLT019", "unwrap or expect in non-test Rust source"),
    ("QLT020", "unsafe Rust marker in non-test Rust source"),
    ("QLT021", "missing cargo-deny policy file"),
    ("QLT022", "missing dependency hygiene script"),
    (
        "QLT023",
        "missing Node package lockfile for browser runtime",
    ),
    (
        "QLT024",
        "config key declared and documented but never read",
    ),
];

pub fn run_repo_quality_checks(root: &Path, cli_reference: &str) -> Result<Vec<Finding>> {
    let mut findings = Vec::new();
    findings.extend(docs_audit::find_missing_required_docs(root));
    findings.extend(docs_audit::find_missing_rule_docs(root)?);
    findings.extend(
        find_reference_doc_drift(root, cli_reference.to_string())?
            .into_iter()
            .map(|path| Finding {
                rule_id: "QLT007".to_string(),
                message: "generated docs drift from code; run `aexeo-cli docs generate .`"
                    .to_string(),
                path: path
                    .strip_prefix(root)
                    .unwrap_or(&path)
                    .to_string_lossy()
                    .replace('\\', "/"),
                line: 1,
                column: 1,
                severity: "error".to_string(),
                suggestion: None,
                scope: FindingScope::Sitewide,
            }),
    );
    findings.extend(tooling_audit::find_static_tooling_issues(root));
    findings.extend(tooling_audit::find_unread_config_keys(root));
    findings.extend(tooling_audit::find_missing_rust_integration_coverage(root));
    findings.extend(rust_audit::find_rust_source_policy_issues(root)?);
    Ok(findings)
}

#[cfg(test)]
mod tests {
    use super::run_repo_quality_checks;
    use crate::docs::write_reference_documents;
    use std::fs;
    use std::path::Path;

    fn write_fixture_file(root: &Path, path: &str, text: &str) {
        if let Some(parent) = Path::new(path).parent() {
            fs::create_dir_all(root.join(parent)).unwrap();
        }
        fs::write(root.join(path), text).unwrap();
    }

    fn write_quality_fixture_root(root: &Path) {
        fs::create_dir_all(root.join("docs")).unwrap();
        fs::create_dir_all(root.join("scripts")).unwrap();
        for path in [
            "CONSTITUTION.md",
            "CONTRACTS.md",
            "SPEC.md",
            "docs/architecture.md",
            "docs/decisions.md",
            "docs/ENGINEERING.md",
            "docs/package-boundaries.md",
            "docs/astro-ci.md",
            "docs/adapters.md",
            "docs/cli.md",
            "docs/config.md",
            "docs/config.schema.json",
            "docs/install.md",
            "docs/local-quality.md",
            "docs/release.md",
            "docs/rules.md",
            "Cargo.toml",
            "deny.toml",
            "scripts/build-rust.sh",
            "scripts/check-deps.sh",
            "scripts/ci-local.sh",
            "scripts/install-hooks.sh",
            "scripts/install-aexeo.sh",
            "package-lock.json",
            "performance-budget.json",
            ".githooks/pre-commit",
            ".githooks/pre-push",
        ] {
            write_fixture_file(root, path, "x");
        }
    }

    #[test]
    fn quality_reports_missing_rust_cli_integration_coverage() {
        let temp_dir = tempfile::tempdir().unwrap();
        let root = temp_dir.path();
        write_quality_fixture_root(root);
        let cli_reference =
            "# CLI Reference\n\n<!-- Generated by aexeo-cli docs generate. Do not edit by hand. -->\n"
                .to_string();
        write_reference_documents(root, cli_reference.clone()).unwrap();
        let findings = run_repo_quality_checks(root, &cli_reference).unwrap();
        assert!(findings.iter().any(|finding| finding.rule_id == "QLT012"));
    }

    #[test]
    fn quality_requires_lockfile_when_browser_runtime_manifest_exists() {
        let temp_dir = tempfile::tempdir().unwrap();
        let root = temp_dir.path();
        write_quality_fixture_root(root);
        write_fixture_file(root, "package.json", "{\"private\":true}\n");
        fs::remove_file(root.join("package-lock.json")).unwrap();
        let cli_reference =
            "# CLI Reference\n\n<!-- Generated by aexeo-cli docs generate. Do not edit by hand. -->\n"
                .to_string();
        write_reference_documents(root, cli_reference.clone()).unwrap();

        let findings = run_repo_quality_checks(root, &cli_reference).unwrap();

        assert!(findings.iter().any(|finding| finding.rule_id == "QLT023"));
    }

    /// Regression: six config keys shipped for a long time as documented,
    /// loader-accepted, `config print`-rendered, and completely inert —
    /// `coverage_threshold`, `complexity_threshold`, `typecheck_command`,
    /// `enable_cache`, `cache_dir`, and `cache_ttl_seconds`. A user setting
    /// `enable_cache = false` changed nothing because there was no cache.
    /// QLT024 is the check that makes that class of rot loud.
    #[test]
    fn quality_reports_a_config_key_that_is_never_read() {
        let temp_dir = tempfile::tempdir().unwrap();
        let root = temp_dir.path();
        write_quality_fixture_root(root);
        // A config.rs declaring one key that is read elsewhere and one that
        // is only declared.
        write_fixture_file(
            root,
            "crates/aexeo-core/src/config.rs",
            "pub struct Config {\n    pub site_url: Option<String>,\n    pub orphan_exclude: Vec<String>,\n}\n",
        );
        // `site_url` is referenced in another module, so it is read.
        write_fixture_file(
            root,
            "crates/aexeo-core/src/policy.rs",
            "pub fn url(config: &Config) -> &str {\n    config.site_url.as_deref().unwrap_or(\"\")\n}\n",
        );
        let cli_reference =
            "# CLI Reference\n\n<!-- Generated by aexeo-cli docs generate. Do not edit by hand. -->\n"
                .to_string();
        write_reference_documents(root, cli_reference.clone()).unwrap();

        let findings = run_repo_quality_checks(root, &cli_reference).unwrap();

        let unread: Vec<&str> = findings
            .iter()
            .filter(|f| f.rule_id == "QLT024")
            .map(|f| f.message.as_str())
            .collect();
        assert_eq!(
            unread.len(),
            1,
            "expected exactly the unread key, got {unread:?}"
        );
        assert!(
            unread[0].contains("orphan_exclude"),
            "the reported key should be the unread one: {unread:?}"
        );
        // The read key must not be reported.
        assert!(
            !unread.iter().any(|m| m.contains("site_url")),
            "a key that is referenced elsewhere must not be reported: {unread:?}"
        );
    }

    #[test]
    fn quality_reports_non_test_unwrap_usage() {
        let temp_dir = tempfile::tempdir().unwrap();
        let root = temp_dir.path();
        write_quality_fixture_root(root);
        write_fixture_file(
            root,
            "crates/example/src/lib.rs",
            "pub fn bad() { let _ = Some(1).unwrap(); }\n",
        );
        write_fixture_file(
            root,
            "crates/aexeo-cli/tests/check_integration.rs",
            "// present\n",
        );
        let cli_reference =
            "# CLI Reference\n\n<!-- Generated by aexeo-cli docs generate. Do not edit by hand. -->\n"
                .to_string();
        write_reference_documents(root, cli_reference.clone()).unwrap();

        let findings = run_repo_quality_checks(root, &cli_reference).unwrap();

        assert!(findings.iter().any(|finding| finding.rule_id == "QLT019"));
    }

    #[test]
    fn quality_ignores_integration_test_unwrap_usage() {
        let temp_dir = tempfile::tempdir().unwrap();
        let root = temp_dir.path();
        write_quality_fixture_root(root);
        write_fixture_file(
            root,
            "crates/example/tests/integration.rs",
            "#[test]\nfn uses_unwrap() {\n    let _ = Some(1).unwrap();\n}\n",
        );
        write_fixture_file(
            root,
            "crates/aexeo-cli/tests/check_integration.rs",
            "// present\n",
        );
        let cli_reference =
            "# CLI Reference\n\n<!-- Generated by aexeo-cli docs generate. Do not edit by hand. -->\n"
                .to_string();
        write_reference_documents(root, cli_reference.clone()).unwrap();

        let findings = run_repo_quality_checks(root, &cli_reference).unwrap();

        assert!(!findings.iter().any(|finding| finding.rule_id == "QLT019"));
    }

    /// Regression: macOS writes `._<name>` AppleDouble resource forks beside
    /// real files on a non-HFS volume, and the sidecar keeps the `.rs`
    /// extension. The source scan read every `*.rs` it found, so one binary
    /// sidecar made `fs::read_to_string` fail and the error propagated out
    /// of `quality` — the gate aborted with "stream did not contain valid
    /// UTF-8" and reported nothing at all, on any checkout that had one.
    #[test]
    fn quality_skips_appledouble_sidecars_instead_of_failing() {
        let temp_dir = tempfile::tempdir().unwrap();
        let root = temp_dir.path();
        write_quality_fixture_root(root);
        write_fixture_file(root, "crates/aexeo-core/src/lib.rs", "// source\n");

        // A real unwrap violation, so the scan has actual work to do.
        write_fixture_file(
            root,
            "crates/aexeo-core/src/rules.rs",
            "pub fn value() -> u8 {\n    Some(1).unwrap()\n}\n",
        );
        // The AppleDouble sidecar for that same file: binary, `.rs` named.
        // Bytes 0x00-0xFF in sequence, which is not valid UTF-8.
        let sidecar: Vec<u8> = (0u8..=255).collect();
        let sidecar_path = root.join("crates/aexeo-core/src/._rules.rs");
        fs::write(sidecar_path, &sidecar).unwrap();
        let cli_reference =
            "# CLI Reference\n\n<!-- Generated by aexeo-cli docs generate. Do not edit by hand. -->\n"
                .to_string();
        write_reference_documents(root, cli_reference.clone()).unwrap();

        // The point of the regression: this must not return an error.
        let findings = run_repo_quality_checks(root, &cli_reference).unwrap();

        // And the scan must still have run, not silently no-op'd.
        assert!(
            findings.iter().any(|finding| finding.rule_id == "QLT019"),
            "expected the real unwrap finding to still be reported; got {findings:?}"
        );
    }

    #[test]
    fn quality_ignores_test_only_unwrap_usage() {
        let temp_dir = tempfile::tempdir().unwrap();
        let root = temp_dir.path();
        write_quality_fixture_root(root);
        write_fixture_file(
            root,
            "crates/example/src/lib.rs",
            "#[cfg(test)]\nmod tests {\n    #[test]\n    fn uses_unwrap() {\n        let _ = Some(1).unwrap();\n    }\n}\n",
        );
        write_fixture_file(
            root,
            "crates/aexeo-cli/tests/check_integration.rs",
            "// present\n",
        );
        let cli_reference =
            "# CLI Reference\n\n<!-- Generated by aexeo-cli docs generate. Do not edit by hand. -->\n"
                .to_string();
        write_reference_documents(root, cli_reference.clone()).unwrap();

        let findings = run_repo_quality_checks(root, &cli_reference).unwrap();

        assert!(!findings.iter().any(|finding| finding.rule_id == "QLT019"));
    }

    #[test]
    fn quality_ignores_string_literals_that_mention_blocked_tokens() {
        let temp_dir = tempfile::tempdir().unwrap();
        let root = temp_dir.path();
        write_quality_fixture_root(root);
        write_fixture_file(
            root,
            "crates/example/src/lib.rs",
            "pub const TOKEN: &str = \".unwrap(\";\n",
        );
        write_fixture_file(
            root,
            "crates/aexeo-cli/tests/check_integration.rs",
            "// present\n",
        );
        let cli_reference =
            "# CLI Reference\n\n<!-- Generated by aexeo-cli docs generate. Do not edit by hand. -->\n"
                .to_string();
        write_reference_documents(root, cli_reference.clone()).unwrap();

        let findings = run_repo_quality_checks(root, &cli_reference).unwrap();

        assert!(!findings.iter().any(|finding| finding.rule_id == "QLT019"));
    }
}
